// Generated by mcp/generate_api.py
minic_register_native("layers_create_fill_layer", mn_layers_create_fill_layer); minic_api_sig_add("layers_create_fill_layer", "v(i uv_type,s:mat4_t decal_mat,i position)");
minic_register_native("ui_files_show", mn_ui_files_show); minic_api_sig_add("ui_files_show", "v(p:char filters,b is_save,b open_multiple,p files_done)");
minic_register_native("ui_files_file_browser", mn_ui_files_file_browser); minic_api_sig_add("ui_files_file_browser", "p:char(p path,b drag_files,p:char search,b refresh,p context_menu)");
minic_register_native("_draw_callback_create", mn__draw_callback_create); minic_api_sig_add("_draw_callback_create", "p:tab_draw_t(p f)");
minic_register_native("import_asset_run", mn_import_asset_run); minic_api_sig_add("import_asset_run", "v(p:char path,f drop_x,f drop_y,b show_box,b hdr_as_envmap,p done)");
minic_register_native("history_object_transform", mn_history_object_transform); minic_api_sig_add("history_object_transform", "v(p:mesh_object_t o,s:vec4_t loc,s:quat_t rot,s:vec4_t scale)");
minic_register_native("ui_menu_draw", mn_ui_menu_draw); minic_api_sig_add("ui_menu_draw", "v(p commands,i x,i y)");
minic_register_native("render_path_base_commands", mn_render_path_base_commands); minic_api_sig_add("render_path_base_commands", "v(p draw_commands)");
minic_register_native("script_screenshot_queue", mn_script_screenshot_queue); minic_api_sig_add("script_screenshot_queue", "v(p:char path,i frames,p done)");
minic_register_native("project_import_mesh", mn_project_import_mesh); minic_api_sig_add("project_import_mesh", "v(b replace_existing,p done)");
minic_register_native("project_import_mesh_box", mn_project_import_mesh_box); minic_api_sig_add("project_import_mesh_box", "v(p:char path,b replace_existing,b clear_layers,b keep_camera,p done)");
minic_register_native("util_render_get_decal_mat", mn_util_render_get_decal_mat); minic_api_sig_add("util_render_get_decal_mat", "s:mat4_t()");
minic_register_native("render_path_raytrace_bake_commands", mn_render_path_raytrace_bake_commands); minic_api_sig_add("render_path_raytrace_bake_commands", "b(p parse_paint_material)");
minic_register_native("util_skin_blob_create", mn_util_skin_blob_create); minic_api_sig_add("util_skin_blob_create", "p:buffer_t(p:char name,i vc,p:f32 pos,p:f32 nor,p:f32 tex,i ic,p:u32 ind,p:u16 joints,p:f32 weights,i jc,i fc,p:f32 mats)");
minic_register_native("ui_box_show_custom", mn_ui_box_show_custom); minic_api_sig_add("ui_box_show_custom", "v(p commands,i mw,i mh,p on_hide,b draggable,p:char title)");
minic_register_native("render_path_raytrace_bake_lightmap", mn_render_path_raytrace_bake_lightmap); minic_api_sig_add("render_path_raytrace_bake_lightmap", "v(p:mesh_object_t object,i res,i samples,f range,p:char path,p done,p:void done_data)");
minic_register_native("text_to_image_node_run", mn_text_to_image_node_run); minic_api_sig_add("text_to_image_node_run", "v(p:ui_node_t node,p callback)");
