// Generated by mcp/generate_api.py
static minic_val_t mn_layers_create_fill_layer(minic_val_t *_a, int _c) {
layers_create_fill_layer((uv_type_t)(minic_arg_i(_a, _c, 0)), M4(1), (i32)(minic_arg_i(_a, _c, 2))); return minic_val_void();
}
static void *mcp_native_ui_files_show_3_fn;
static void mcp_native_ui_files_show_3(char * arg) { minic_val_t a = minic_val_ptr(arg); minic_call_fn(mcp_native_ui_files_show_3_fn, &a, 1); }
static minic_val_t mn_ui_files_show(minic_val_t *_a, int _c) {
mcp_native_ui_files_show_3_fn = AP(3);
ui_files_show((char *)(AP(0)), (bool)(minic_arg_i(_a, _c, 1)), (bool)(minic_arg_i(_a, _c, 2)), (AP(3) != NULL ? mcp_native_ui_files_show_3 : NULL)); return minic_val_void();
}
static void *mcp_native_ui_files_file_browser_4_fn;
static void mcp_native_ui_files_file_browser_4(char * arg) { minic_val_t a = minic_val_ptr(arg); minic_call_fn(mcp_native_ui_files_file_browser_4_fn, &a, 1); }
static minic_val_t mn_ui_files_file_browser(minic_val_t *_a, int _c) {
mcp_native_ui_files_file_browser_4_fn = AP(4);
return minic_val_ptr(ui_files_file_browser((char **)(AP(0)), (bool)(minic_arg_i(_a, _c, 1)), (char *)(AP(2)), (bool)(minic_arg_i(_a, _c, 3)), (AP(4) != NULL ? mcp_native_ui_files_file_browser_4 : NULL)));
}
static void *mcp_native__draw_callback_create_0_fn;
static void mcp_native__draw_callback_create_0(i32 * arg) { minic_val_t a = minic_val_ptr(arg); minic_call_fn(mcp_native__draw_callback_create_0_fn, &a, 1); }
static minic_val_t mn__draw_callback_create(minic_val_t *_a, int _c) {
mcp_native__draw_callback_create_0_fn = AP(0);
return minic_val_ptr(_draw_callback_create((AP(0) != NULL ? mcp_native__draw_callback_create_0 : NULL)));
}
static void *mcp_native_import_asset_run_5_fn;
static void mcp_native_import_asset_run_5(void) { minic_call_fn(mcp_native_import_asset_run_5_fn, NULL, 0); }
static minic_val_t mn_import_asset_run(minic_val_t *_a, int _c) {
mcp_native_import_asset_run_5_fn = AP(5);
import_asset_run((char *)(AP(0)), (f32)(AF(1)), (f32)(AF(2)), (bool)(minic_arg_i(_a, _c, 3)), (bool)(minic_arg_i(_a, _c, 4)), (AP(5) != NULL ? mcp_native_import_asset_run_5 : NULL)); return minic_val_void();
}
static minic_val_t mn_history_object_transform(minic_val_t *_a, int _c) {
history_object_transform((mesh_object_t *)(AP(0)), V4(1), QT(2), V4(3)); return minic_val_void();
}
static void *mcp_native_ui_menu_draw_0_fn;
static void mcp_native_ui_menu_draw_0(void) { minic_call_fn(mcp_native_ui_menu_draw_0_fn, NULL, 0); }
static minic_val_t mn_ui_menu_draw(minic_val_t *_a, int _c) {
mcp_native_ui_menu_draw_0_fn = AP(0);
ui_menu_draw((AP(0) != NULL ? mcp_native_ui_menu_draw_0 : NULL), (i32)(minic_arg_i(_a, _c, 1)), (i32)(minic_arg_i(_a, _c, 2))); return minic_val_void();
}
static void *mcp_native_render_path_base_commands_0_fn;
static void mcp_native_render_path_base_commands_0(void) { minic_call_fn(mcp_native_render_path_base_commands_0_fn, NULL, 0); }
static minic_val_t mn_render_path_base_commands(minic_val_t *_a, int _c) {
mcp_native_render_path_base_commands_0_fn = AP(0);
render_path_base_commands((AP(0) != NULL ? mcp_native_render_path_base_commands_0 : NULL)); return minic_val_void();
}
static void *mcp_native_script_screenshot_queue_2_fn;
static void mcp_native_script_screenshot_queue_2(void) { minic_call_fn(mcp_native_script_screenshot_queue_2_fn, NULL, 0); }
static minic_val_t mn_script_screenshot_queue(minic_val_t *_a, int _c) {
mcp_native_script_screenshot_queue_2_fn = AP(2);
script_screenshot_queue((char *)(AP(0)), (i32)(minic_arg_i(_a, _c, 1)), (AP(2) != NULL ? mcp_native_script_screenshot_queue_2 : NULL)); return minic_val_void();
}
static void *mcp_native_project_import_mesh_1_fn;
static void mcp_native_project_import_mesh_1(void) { minic_call_fn(mcp_native_project_import_mesh_1_fn, NULL, 0); }
static minic_val_t mn_project_import_mesh(minic_val_t *_a, int _c) {
mcp_native_project_import_mesh_1_fn = AP(1);
project_import_mesh((bool)(minic_arg_i(_a, _c, 0)), (AP(1) != NULL ? mcp_native_project_import_mesh_1 : NULL)); return minic_val_void();
}
static void *mcp_native_project_import_mesh_box_4_fn;
static void mcp_native_project_import_mesh_box_4(void) { minic_call_fn(mcp_native_project_import_mesh_box_4_fn, NULL, 0); }
static minic_val_t mn_project_import_mesh_box(minic_val_t *_a, int _c) {
mcp_native_project_import_mesh_box_4_fn = AP(4);
project_import_mesh_box((char *)(AP(0)), (bool)(minic_arg_i(_a, _c, 1)), (bool)(minic_arg_i(_a, _c, 2)), (bool)(minic_arg_i(_a, _c, 3)), (AP(4) != NULL ? mcp_native_project_import_mesh_box_4 : NULL)); return minic_val_void();
}
static minic_val_t mn_util_render_get_decal_mat(minic_val_t *_a, int _c) {
mat4_t *result = minic_alloc(sizeof(mat4_t)); if (result == NULL) return minic_val_ptr(NULL); *result = util_render_get_decal_mat(); return minic_val_ptr(result);
}
static void *mcp_native_render_path_raytrace_bake_commands_0_fn;
static void mcp_native_render_path_raytrace_bake_commands_0(bool arg) { minic_val_t a = minic_val_int(arg); minic_call_fn(mcp_native_render_path_raytrace_bake_commands_0_fn, &a, 1); }
static minic_val_t mn_render_path_raytrace_bake_commands(minic_val_t *_a, int _c) {
mcp_native_render_path_raytrace_bake_commands_0_fn = AP(0);
return minic_val_int(render_path_raytrace_bake_commands((AP(0) != NULL ? mcp_native_render_path_raytrace_bake_commands_0 : NULL)));
}
static minic_val_t mn_util_skin_blob_create(minic_val_t *_a, int _c) {
return minic_val_ptr(util_skin_blob_create((char *)(AP(0)), (i32)(minic_arg_i(_a, _c, 1)), (f32 *)(AP(2)), (f32 *)(AP(3)), (f32 *)(AP(4)), (i32)(minic_arg_i(_a, _c, 5)), (u32 *)(AP(6)), (u16 *)(AP(7)), (f32 *)(AP(8)), (i32)(minic_arg_i(_a, _c, 9)), (i32)(minic_arg_i(_a, _c, 10)), (f32 *)(AP(11))));
}
static void *mcp_native_ui_box_show_custom_0_fn;
static void mcp_native_ui_box_show_custom_0(void) { minic_call_fn(mcp_native_ui_box_show_custom_0_fn, NULL, 0); }
static void *mcp_native_ui_box_show_custom_3_fn;
static void mcp_native_ui_box_show_custom_3(void) { minic_call_fn(mcp_native_ui_box_show_custom_3_fn, NULL, 0); }
static minic_val_t mn_ui_box_show_custom(minic_val_t *_a, int _c) {
mcp_native_ui_box_show_custom_0_fn = AP(0);
mcp_native_ui_box_show_custom_3_fn = AP(3);
ui_box_show_custom((AP(0) != NULL ? mcp_native_ui_box_show_custom_0 : NULL), (i32)(minic_arg_i(_a, _c, 1)), (i32)(minic_arg_i(_a, _c, 2)), (AP(3) != NULL ? mcp_native_ui_box_show_custom_3 : NULL), (bool)(minic_arg_i(_a, _c, 4)), (char *)(AP(5))); return minic_val_void();
}
static void *mcp_native_render_path_raytrace_bake_lightmap_5_fn;
static void mcp_native_render_path_raytrace_bake_lightmap_5(void * arg) { minic_val_t a = minic_val_ptr(arg); minic_call_fn(mcp_native_render_path_raytrace_bake_lightmap_5_fn, &a, 1); }
static minic_val_t mn_render_path_raytrace_bake_lightmap(minic_val_t *_a, int _c) {
mcp_native_render_path_raytrace_bake_lightmap_5_fn = AP(5);
render_path_raytrace_bake_lightmap((mesh_object_t *)(AP(0)), (i32)(minic_arg_i(_a, _c, 1)), (i32)(minic_arg_i(_a, _c, 2)), (f32)(AF(3)), (char *)(AP(4)), (AP(5) != NULL ? mcp_native_render_path_raytrace_bake_lightmap_5 : NULL), (void *)(AP(6))); return minic_val_void();
}
static void *mcp_native_text_to_image_node_run_1_fn;
static void mcp_native_text_to_image_node_run_1(ui_node_t * arg) { minic_val_t a = minic_val_ptr(arg); minic_call_fn(mcp_native_text_to_image_node_run_1_fn, &a, 1); }
static minic_val_t mn_text_to_image_node_run(minic_val_t *_a, int _c) {
mcp_native_text_to_image_node_run_1_fn = AP(1);
text_to_image_node_run((ui_node_t *)(AP(0)), (AP(1) != NULL ? mcp_native_text_to_image_node_run_1 : NULL)); return minic_val_void();
}
