"""Generate script bindings from ArmorPaint's own declarations.

Run after upstream changes. By-value structs and native callback arguments need
hand-written adapters; the report lists them instead of inventing an unsafe ABI.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "paint/sources"


def clean(text):
    return re.sub(r"/\*.*?\*/|//[^\n]*", "", text, flags=re.S)


def generate():
    enums = clean((SRC / "enums.h").read_text())
    enum_types = set(re.findall(r"}\s*(\w+_t)\s*;", enums))
    enum_types.update(re.findall(r"}\s*(\w+_t)\s*;", clean((ROOT / "base/sources/iron_ui.h").read_text())))
    existing = set(re.findall(r"^X\d+\((\w+),", (SRC / "minic_api_list.h").read_text(), re.M))
    existing.update(re.findall(r"^\s*X\(\w+,\s*(\w+),", (SRC / "minic_api.c").read_text(), re.M))
    scalar = {"void": "v", "bool": "b", "int": "i", "i32": "i", "u32": "i", "uint32_t": "i", "uint16_t": "i", "u16": "i", "i16": "i", "u8": "i", "f32": "f", "float": "f", "f64": "d", "double": "d"}

    def kind(ctype):
        if "*" in ctype:
            return "p"
        return scalar.get(ctype, "i" if ctype in enum_types else None)

    lines = ["// Generated by mcp/generate_api.py; do not edit. No include guard: X-macro list."]
    skipped = []
    exposed = []
    adapters = []
    native = ["// Generated by mcp/generate_api.py"]
    registration = ["// Generated by mcp/generate_api.py"]
    value_types = {"vec4_t": ("V4", "V4"), "quat_t": ("Q", "QT"), "mat4_t": ("M4", "M4")}
    unavailable = {"ui_base_update_ui", "util_mesh_equirect_unwrap"}
    guards = {name: "IRON_WASM" for name in ("base_share_player", "box_projects_cloud_save_show", "box_projects_cloud_slot", "box_projects_cloud_tab", "box_projects_is_cloud_path")}
    guards["config_is_iphone"] = "IRON_IOS"
    header = clean((SRC / "functions.h").read_text())
    for decl in header.split(";"):
        decl = re.sub(r"^\s*#.*$", "", decl, flags=re.M).strip()
        match = re.fullmatch(r"([\w\s*]+?)\s*(\w+)\s*\((.*?)\)", decl, re.S)
        if not match:
            continue
        ret, name, params = match.groups()
        if name in existing or name.startswith("mcp_"):
            continue
        ret = " ".join(ret.split())
        if name in unavailable:
            skipped.append({"name": name, "declaration": decl + ";", "reason": "declared upstream but has no implementation"})
            continue
        args = []
        reason = None
        for param in params.split(",") if params.strip() not in ("", "void") else []:
            m = re.fullmatch(r"\s*([\w\s*]+?)\s*(\w+)\s*", param)
            if not m or not kind(" ".join(m[1].split())):
                reason = "native callback or by-value struct argument"
                break
            args.append((" ".join(m[1].split()), m[2]))
        if kind(ret) is None or len(args) > 10:
            reason = "by-value struct return or unsupported arity"
        if reason:
            calls, sig_args = [], []
            for index, param in enumerate(params.split(",") if params.strip() not in ("", "void") else []):
                callback = re.fullmatch(r"\s*void\s*\(\*(\w+)\)\s*\((.*?)\)\s*", param, re.S)
                m = re.fullmatch(r"\s*([\w\s*]+?)\s*(\w+)\s*", param)
                if callback:
                    arg_name, cb_type = callback.groups()
                    cb_name = f"mcp_native_{name}_{index}"
                    native.append(f"static void *{cb_name}_fn;")
                    if cb_type.strip() == "void":
                        native.append(f"static void {cb_name}(void) {{ minic_call_fn({cb_name}_fn, NULL, 0); }}")
                    elif "*" in cb_type:
                        native.append(f"static void {cb_name}({cb_type} arg) {{ minic_val_t a = minic_val_ptr(arg); minic_call_fn({cb_name}_fn, &a, 1); }}")
                    elif cb_type.strip() == "bool":
                        native.append(f"static void {cb_name}(bool arg) {{ minic_val_t a = minic_val_int(arg); minic_call_fn({cb_name}_fn, &a, 1); }}")
                    else:
                        break
                    calls.append(f"(AP({index}) != NULL ? {cb_name} : NULL)")
                    sig_args.append(f"p {arg_name}")
                elif m:
                    ctype, arg_name = " ".join(m[1].split()), m[2]
                    k = kind(ctype)
                    if ctype in value_types:
                        calls.append(f"{value_types[ctype][1]}({index})")
                        sig_args.append(f"s:{ctype} {arg_name}")
                    elif k:
                        access = f"AP({index})" if k == "p" else f"AF({index})" if k == "f" else f"minic_val_to_d(_a[{index}])" if k == "d" else f"minic_arg_i(_a, _c, {index})"
                        calls.append(f"({ctype})({access})")
                        sig_args.append(k + (":" + ctype.replace("*", "").strip() if k == "p" and ctype.count("*") == 1 else "") + " " + arg_name)
                    else:
                        break
                else:
                    break
            else:
                rk = kind(ret)
                if rk or ret in value_types:
                    sig_ret = "s:" + ret if ret in value_types else "p:" + ret.replace("*", "").strip() if rk == "p" and ret.count("*") == 1 else rk
                    sig = sig_ret + "(" + ",".join(sig_args) + ")"
                    native.append(f"static minic_val_t mn_{name}(minic_val_t *_a, int _c) {{")
                    for index, param in enumerate(params.split(",")):
                        if "(*" in param:
                            native.append(f"mcp_native_{name}_{index}_fn = AP({index});")
                    call = f"{name}({', '.join(calls)})"
                    if ret in value_types:
                        native.append(f"{ret} *result = minic_alloc(sizeof({ret})); if (result == NULL) return minic_val_ptr(NULL); *result = {call}; return minic_val_ptr(result);")
                    elif rk == "v":
                        native.append(call + "; return minic_val_void();")
                    else:
                        convert = {"p": "minic_val_ptr", "i": "minic_val_int", "b": "minic_val_int", "f": "minic_val_float", "d": "minic_val_double"}[rk]
                        native.append(f"return {convert}({call});")
                    native.append("}")
                    registration.append(f'minic_register_native("{name}", mn_{name}); minic_api_sig_add("{name}", "{sig}");')
                    adapters.append(name)
                    continue
            skipped.append({"name": name, "declaration": decl + ";", "reason": reason})
            continue
        rk = kind(ret)
        rsig = "p:" + ret.replace("*", "").strip() if rk == "p" and ret.count("*") == 1 and ret.strip() != "void *" else rk
        sig = rsig + "(" + ",".join(kind(t) + (":" + t.replace("*", "").strip() if kind(t) == "p" and t.count("*") == 1 else "") + " " + n for t, n in args) + ")"
        if name in guards:
            lines.append(f"#ifdef {guards[name]}")
        lines.append(f'X{len(args)}({name}, "{sig}", {rk}' + "".join(", " + kind(t) for t, n in args) + ")")
        if name in guards:
            lines.append("#endif")
        exposed.append(name)
    (SRC / "minic_api_extra.h").write_text("\n".join(lines) + "\n")
    (SRC / "minic_native_extra.h").write_text("\n".join(native) + "\n")
    (SRC / "minic_native_register.h").write_text("\n".join(registration) + "\n")

    # Register application enum constants, including explicitly assigned values.
    constants = []
    for block, typ in re.findall(r"typedef enum\s*{(.*?)}\s*(\w+)\s*;", enums, re.S):
        constants.append(f'minic_int_typedef_add("{typ}");')
        for value in block.split(","):
            name = value.split("=")[0].strip()
            if re.fullmatch(r"\w+", name):
                constants.append(f'minic_enum_const_add("{name}", {name});')
    (SRC / "minic_enum_extra.h").write_text("// Generated by mcp/generate_api.py\n" + "\n".join(constants) + "\n")

    # Expose application struct fields using actual C offsets. Keep the existing
    # context/config bindings; their complete scalar settings are exposed below.
    structs = []
    settings = []
    types = clean((SRC / "types.h").read_text())
    registered = set(re.findall(r"MINIC_STRUCT\((\w+)\)", (SRC / "minic_api.c").read_text()))
    for block, typ in re.findall(r"typedef struct(?:\s+\w+)?\s*{(.*?)}\s*(\w+)\s*;", types, re.S):
        if typ in registered and typ not in ("context_t", "config_t", "project_t"):
            continue
        block = re.sub(r"struct\s*{[^{}]*}\s*\w+(?:\[\d+\])?\s*;", "", block, flags=re.S)
        fields = []
        for field in block.split(";"):
            m = re.fullmatch(r"\s*([\w\s*]+?)\s*(\w+)\s*", field)
            if not m:
                continue
            ctype, name = " ".join(m[1].split()), m[2]
            k = kind(ctype)
            if typ in ("context_t", "config_t"):
                if k in ("b", "i", "f", "d"):
                    settings.append((typ, name, k))
                continue
            if k in ("b", "i", "f"):
                fields.append(f"MINIC_{k.upper()}({name});")
            elif k == "d":
                fields.append(f"MINIC_FIELD({name}, MINIC_T_DOUBLE, MINIC_T_DOUBLE, NULL);")
            elif k == "p":
                base = ctype.replace("struct ", "").replace("*", "").strip()
                if base == "char" and ctype.count("*") == 1:
                    fields.append(f"MINIC_S({name});")
                elif ctype.count("*") == 1 and base != "void":
                    stype = base if base.endswith("_t") else base + "_t"
                    fields.append(f"MINIC_O({name}, {stype});")
                else:
                    fields.append(f"MINIC_P({name});")
            elif ctype in ("vec4_t", "quat_t", "mat4_t"):
                fields.append(f"MINIC_E({name}, {ctype});")
        if fields:
            if len(fields) > 64:
                raise ValueError(f"{typ} has {len(fields)} fields; increase MINIC_MAX_STRUCT_FIELDS")
            structs.extend([f"MINIC_STRUCT({typ});", *fields, "MINIC_END();"])
    (SRC / "minic_struct_extra.h").write_text("// Generated by mcp/generate_api.py\n" + "\n".join(structs) + "\n")
    settings_lines = ["// Generated by mcp/generate_api.py; use with S(type, field, kind)."]
    settings_lines += [f"S({t}, {n}, {k})" for t, n, k in settings]
    (SRC / "mcp_settings.h").write_text("\n".join(settings_lines) + "\n")
    report = {"additional_functions": len(exposed) + len(adapters), "functions": exposed, "native_adapters": adapters, "scalar_settings": len(settings), "requires_adapter": skipped}
    (ROOT / "mcp/api_coverage.json").write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n")
    print(f"Generated {len(exposed)} simple bindings, {len(adapters)} native adapters, {len(settings)} settings; {len(skipped)} declarations unavailable.")


if __name__ == "__main__":
    generate()
